# Generated by Django 4.2.5 on 2023-09-21 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_comments_bids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="created",
        ),
        migrations.AddField(
            model_name="listing",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
