# Generated by Django 4.2.5 on 2023-09-21 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_listing_created_listing_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="date",
        ),
        migrations.AddField(
            model_name="comments",
            name="date_comment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
