# Generated by Django 4.2.5 on 2023-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_category_rename_starting_bid_listing_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
