# Generated by Django 4.2.5 on 2023-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_listing_watch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bids",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="bids",
            name="item",
        ),
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=9),
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.ManyToManyField(
                blank=True, related_name="bids", to="auctions.bids"
            ),
        ),
    ]
