# Generated by Django 4.2.5 on 2023-09-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_remove_bids_amount_remove_bids_item_bids_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.AddField(
            model_name="bids",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_bid",
                to="auctions.listing",
            ),
        ),
    ]
