# Generated by Django 4.2.5 on 2023-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_remove_listing_price_bids_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid",
            field=models.FloatField(default="0"),
        ),
    ]
