# Generated by Django 4.2.5 on 2023-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_bids_bid_alter_bids_item_alter_bids_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
