# Generated by Django 4.2.5 on 2023-10-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_listing_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bids",
            name="item",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="item",
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Bids",
                to="auctions.bids",
            ),
        ),
    ]
