# Generated by Django 4.2.5 on 2023-10-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_remove_bids_item_remove_comments_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.comments",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.bids",
            ),
        ),
    ]
