# Generated by Django 4.2.5 on 2023-10-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_listing_comments_alter_listing_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="comments",
        ),
        migrations.AddField(
            model_name="comments",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_comment",
                to="auctions.listing",
            ),
        ),
    ]
