# Generated by Django 4.2.5 on 2023-10-03 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_remove_listing_comments_comments_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.AddField(
            model_name="bids",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_bids",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="bids",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
