# Generated by Django 4.2.5 on 2023-10-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_remove_listing_price_bids_item_alter_bids_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="start_price",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="bids",
            name="bid",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category",
                to="auctions.category",
            ),
        ),
    ]
