# Generated by Django 4.2.5 on 2023-10-03 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0021_listing_buyer_listing_current_bid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="start_price",
            new_name="starting_price",
        ),
    ]
